services:
  postgres:
    container_name: ML_DB
    image: postgres
    hostname: localhost
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./_Setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./_Setup/user.sql:/docker-entrypoint-initdb.d/user.sql
    restart: unless-stopped
    env_file:
      - .env

  aspnetapp:
    container_name: aspnetapp
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Release

volumes:
  postgres-data: 
    name: ML-DB