services:
  postgres:
    container_name: ML_DB
    image: postgres
    hostname: localhost
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
    restart: unless-stopped
    env_file:
      - .env

  pgadmin:
    container_name: ML_DB-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres-data: 
    name: ML-DB